create database if not exists Loja;

use Loja;

CREATE TABLE IF NOT EXISTS TB_CLIENTE (
ID_CLIENTE INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOME_CLIENTE VARCHAR (60) NOT NULL,
END_CLIENTE CHAR (120) NOT NULL,
EMAIL_CLIENTE VARCHAR (35) NOT NULL UNIQUE,
SENHA_CLIENTE VARCHAR (20) NOT NULL
)engine=InnoDB;
 
CREATE TABLE IF NOT EXISTS TB_PROD (
ID_PROD INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOME_PROD VARCHAR (40) NOT NULL UNIQUE,
VALOR_PROD NUMERIC (6,2) NOT NULL,
IMAGEM_PROD VARCHAR (255),
DESC_PROD TEXT NOT NULL 
)engine=InnoDB;

CREATE TABLE IF NOT EXISTS TB_PEDIDO (
ID_PEDIDO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
DTA_PEDIDO DATETIME NOT NULL,
VALOR_PEDIDO NUMERIC (7,2) NOT NULL,
STATUS_PEDIDO VARCHAR (40) NOT NULL,
ID_CLIENTE INT NOT NULL,
ID_PROD INT NOT NULL,
COND_PAGTO INT NOT NULL,
FORM_PAGTO INT NOT NULL,
VALOR_PARCE DECIMAL (7,2),
FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE(ID_CLIENTE),
FOREIGN KEY (ID_PROD) REFERENCES TB_PROD(ID_PROD)
)engine=InnoDB;

INSERT INTO TB_PROD (NOME_PROD, VALOR_PROD, DESC_PROD, IMAGEM_PROD)
VALUES 
('Camiseta Polo', 59.90, 'Camiseta polo masculina, disponível em várias cores.','img/camiseta_polo'),
('Tênis Esportivo', 199.99, 'Tênis esportivo para corrida e caminhada, confortável e resistente.', 'img/tenis_esportivo'),
('Relógio de Pulso', 299.90, 'Relógio de pulso masculino, estilo clássico e elegante.', 'img/tenis_esportivo');
